
services:
  web:
    build:
      context: compose/production/django/.
    container_name: django_web_reservations
    command: pipenv run python manage.py runserver 0.0.0.0:8080
    environment:
      - DEBUG=true
      - TEMPLATE_DEBUG=true
      - PYTHONUNBUFFERED=true
      - IS_MIGRATION=False
    networks:
      - network_django
    volumes:
      - .:/project
    restart: always



  # database
  db:
    image: postgres:latest
    container_name: db_reservations
    ports:
      - "5433:5432"
    volumes:
      - reservations-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=reservations
      - POSTGRES_USER=reservations
      - POSTGRES_PASSWORD=reservations
    networks:
      - network_django

    restart: always


volumes:
  reservations-data:
networks:
  network_django:
    name: network_reservations
    external: true