# Generated by Django 5.0.2 on 2024-10-20 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='status',
            field=models.PositiveIntegerField(choices=[(0, 'Review'), (1, 'Rejected'), (2, 'Confirmed')], default=0),
        ),
    ]
