# Generated by Django 5.0.2 on 2024-06-20 01:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_remove_category_sub_category_remove_company_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sansconfig',
            name='duration_time',
        ),
        migrations.AlterField(
            model_name='sansconfig',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='company.company'),
        ),
        migrations.AlterField(
            model_name='sansconfig',
            name='duration',
            field=models.IntegerField(default=30),
        ),
        migrations.DeleteModel(
            name='SansHolidayDateTime',
        ),
    ]
